Testing cam assignment
Traceback (most recent call last):
  File "/home/alarm/git/raspberry/src/Cam.py", line 68, in <module>
    cam = Cam(arg_d)
  File "/home/alarm/git/raspberry/src/Cam.py", line 48, in __init__
    self.cam[key] = value
TypeError: 'PiCamera' object does not support item assignment

trying to see if its a problem with the for loop or assignment in
general but rly want it to work otherwise will need to be assigned by
hand